name: Python App

on:
  push:
    branches:
      - main  # Runs tests when you push to the main branch
  pull_request:
    branches:
      - main  # Runs tests when a pull request is made to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover app/tests
